### ISSUE TITLE
Add a flag to allow "non-strict" mode

### ISSUE THREAD

**Issue by derekstavis** [dumconstantin/ramda-loader#7]
I like the idea of automatic Ramda imports, but it makes a lot of sense for me having functions names like `find` on my models, for example. Because of this issue I'd like to propose an addition query to configure this loader to not automatically add imports.

I have implemented this as `strict=false`. This way, we can still have Ramda debugging facilities while not adding global imports.

What do you think about?
Thanks!

**Comment by orther** [comment]
I have an existing codebase with several other developers that would benefit from the debugging facilities but not the automatic import. We automatically provide ramda in the global scope on demand with webpack ProviderPlugin and use `R.` prefix.

Are you willing to add a flag to disable global imports?

**Comment by dumconstantin** [comment]
Hi guys,

Sorry for the late response. Sure, it makes a lot of sense.

@derekstavis Do you have a fork with the ``` strict=false ``` flag implemented? If so, you could make a pull request and I'll merge it. Otherwise I'll get that implemented.

@orther Sure, I'll implemented a ``` imports=true | false ``` flag. 

Thanks!

**Comment by dumconstantin** [comment]
I've added both flags in v 0.5.0.

I'm closing this as it solves @derekstavis issue.

However, I realized that your issue @orther is not solved by the ``` imports ``` flag as you need ``` ramda-loader ``` to detect fn calls that have the ``` R ``` namespace. 

To this end, I've created https://github.com/dumconstantin/ramda-loader/issues/9 to address just this.
