### ISSUE TITLE
Reserved words

### ISSUE THREAD

**Issue by ivan-kleshnin** [dumconstantin/ramda-loader#8]
What about Ramda functions which are reserved words like `is`?

**Comment by dumconstantin** [comment]
Hi @ivan-kleshnin,

From what I know Ramda function names do not use reserved words...
According to [MDN - Reserved Words](http://mdn.beonex.com/en/JavaScript/Reference/Reserved_Words.html) ``` is ``` doesn't appear to be a reserved word.

But if you try using ``` is ``` with ``` ramda-loader ``` you shouldn't get any compiler errors.

Let me know if this was an issue for you and we'll see how we can fix it.

**Comment by ivan-kleshnin** [comment]
Yes, `is` was a wrong example. I remember there were such functions previously. For example, https://github.com/ramda/ramda/issues/553 but they all seem to be removed for now.

@dumconstantin btw, did you try to use this approach for backend development? I'm curious about the amount of pros and cons of Weback bundling for backend – maybe you gave it a try.

**Comment by dumconstantin** [comment]
Hi @ivan-kleshnin, yes I use this approach on the backend too. 

I didn't realize at the time that I could've write ``` ramda-loader ``` as a Babel plugin. That would've made it much more portable... but I didn't have time do to so later.

So a quick fix for me was through a gulp process that injects all of Ramda's functions at the beginning of every file right before sending it off to Babel for transpiling. However, I did lose out on the debugging features that ``` ramda-loader ``` has. (let me know if you'd need this code).

If you want to use Webpack for node, you can just specify ``` commonjs ``` as your output target and it will work.

The cons of using Webpack on node is that it will bundle everything into a single file (including deps). While there are some use cases for that (portability I guess) most commonly you would like to keep the folder structure intact.
